language: python
sudo: required
python:
- '2.7'
- pypy
install:
- pip install -r requirements/dev.txt
env:
  global:
  - secure: AH2kilknG5lcHAvwg3GSLepB/jecSvz11OO83+jDIhaZJN4vY7TFMot/P21Yd73BgjY5O5fU9XtXwG/bd+tYJvge1N6l9YvTNnrMeYApgjPMfucRQJhp1Teg5PZ97ImVPYpEIorsrds6JimcPgeZBWuNR+1Shudv9uAEMP6NM/nATw3q7r9nUtTQ2XRs+IGh4vqE0z9pllD4tT8t5l/VKS8jjfpz+NRjBNV0CSDLZiFH0PgV3mRXTB0AAhtTYlT0uaVFJtSwo75s2OleCCUQVNGtNnZ1tMHVgxCEVgLRBA0x50hdB71mdhpzntXZ2uLjzCGcJ4eJJeu5+Wq2xsD/tfC5JH2Fdkd+LFdQ2mTwFXqscCggo3eDoIBESKMztaRoXIZKydX52JPv2AqnBkjDLEVZJcaKalvHTeiPcSUWhNpd0yCNXkn/CDdo+k4RTAemWcwkQvmWt55vaKkIgkwKGznfQ1E0BR7Bi4+XiC4aykF04co3gd2YjoFOCZHrcpuzW+w6w31Po20rOwDJQgWHDk/f7Mnvl2DpzrIdFOCVNnKmdi80dULJA5E5l5oPALjgpCgSpdgasaaUDFcLSzNrRiXcxOmns7Y/6G2vzBFrjAfF02Bj38xRMTbut44WSbviz6dE9cT8pdQoO9lvvDRwrua4DspVgPO37H5CY9aSa5Q=
script:
- export RESCUETIME=$RESCUETIME
- make tests
