language: python
sudo: required
python:
- '2.7'
- pypy
install:
- pip install -r requirements/dev.txt
env:
  global:
  - secure: AH2kilknG5lcHAvwg3GSLepB/jecSvz11OO83+jDIhaZJN4vY7TFMot/P21Yd73BgjY5O5fU9XtXwG/bd+tYJvge1N6l9YvTNnrMeYApgjPMfucRQJhp1Teg5PZ97ImVPYpEIorsrds6JimcPgeZBWuNR+1Shudv9uAEMP6NM/nATw3q7r9nUtTQ2XRs+IGh4vqE0z9pllD4tT8t5l/VKS8jjfpz+NRjBNV0CSDLZiFH0PgV3mRXTB0AAhtTYlT0uaVFJtSwo75s2OleCCUQVNGtNnZ1tMHVgxCEVgLRBA0x50hdB71mdhpzntXZ2uLjzCGcJ4eJJeu5+Wq2xsD/tfC5JH2Fdkd+LFdQ2mTwFXqscCggo3eDoIBESKMztaRoXIZKydX52JPv2AqnBkjDLEVZJcaKalvHTeiPcSUWhNpd0yCNXkn/CDdo+k4RTAemWcwkQvmWt55vaKkIgkwKGznfQ1E0BR7Bi4+XiC4aykF04co3gd2YjoFOCZHrcpuzW+w6w31Po20rOwDJQgWHDk/f7Mnvl2DpzrIdFOCVNnKmdi80dULJA5E5l5oPALjgpCgSpdgasaaUDFcLSzNrRiXcxOmns7Y/6G2vzBFrjAfF02Bj38xRMTbut44WSbviz6dE9cT8pdQoO9lvvDRwrua4DspVgPO37H5CY9aSa5Q=
  - secure: TrixgMxHaS+SWL4ErA1+eIc1Vr9wbjgeKSH1wKh/RonFdMt0IBKO1ZvlECd0ckQoIzkJWI7oeZZNBqsgPjOq22oRP0vHNJS9Ny0HfufRpRq8u0qQ7qqi4BS0kJJShMzW1XcKy4vJ70Jd8W3vGP6XqxEAYNtroaItOQPMQCSog0OT2BJapkF+WI6bt79BZRtHeGKIscfy+LWn64QyxMusHSkURqsdkokoZodLtpymNGif5ZeFFQq1DVXh51piN9erOD3Kd+qG1xhk0RvYJFIvyv0TFennch6cKzhGacTQrgXOFVR4GdwZXM4lLku3FSwmC5Ed52jSSmqN37JF5mma1AIpjHMxLiS0JfWxfd2frWcuVN4TYlsUU9wRjrSQeQbU4DQMmAhNz4N6GDqkydHY3bZavbT+V7uq2yq4F0uCH/req1Z33lHRCCCNXbHZpYXqi8gC476ph95dfg5gqnZuMayvUJb6keJ9Gjtkqpy+w5Pj4tWg7ghJ4y+AgbqWt2mBcWpfZq0+9U64xxjiY1xyfdY70AqFE+ps31j8DDBnwHMEDRg62671QWvXbvuKXzc1mcWEWX1W3pMUgL/AZjH6rC1Qelg4bM7OR5MUKbuqA78ApgtFgIWv5MdT1y8A/esummUxWP+qf2Rx/F0Acw3uCTo+uUBKUqt2h4pUrQz01TY=
script:
- export RESCUETIME=$RESCUETIME
- export FOURSQUARE=$FOURSQUARE
- make tests
